### ISSUE TITLE
Add Walks-component

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#15]
## User Story
As a user 
I want to add the walks I did with my dog already
So that I can see how much time I should go outside with him afterwards

## Design/Wireframe
![inputwalk(1)](https://user-images.githubusercontent.com/100389763/175488255-1773a2c0-5e9a-4749-80e6-081c34bfc525.png)

## AC
- [x] an option to add new walks
- [x] the user should have an option to select between the duration or the timeframe of the walk
- [x] the user should be able to input the starting-time of the walk
- [x] the user should be able to open up the input-selection
- [x] the user should see when the last walk was
- [x] the user should see how long their last walk was

## Tasks
- [x] create new branch
- [x] add inputWalk-component
- [x] add a form so that the user can input when and for how long the last dog walk was
- [x] add a button to the displayWalks-component to display the form
- [x] connect the inputWalk-component to the button-click (?conditional templates)
- [x] apply basic styling to form
- [x] update given item-card-elements with the submitted input

## Complexity
M

## Depends on
#16

**Comment by dananhsl** [comment]
Hey Yannik! I really like this User Story, although I think that it could be a bit too much, to add two full components plus functionality in one user story. Try cutting it a bit shorter and maybe split it into two seperate stories. 🐶

**Comment by yannhn** [comment]
Thanks for the Feedback and the help! I added a new user story just to display the walks and updated the above one to just be about the input. 

https://github.com/yannhn/capstone-project/issues/16

**Comment by dananhsl** [comment]
Well done! I like it!

**Comment by yannhn** [comment]
Thanks!🐶

**Comment by yannhn** [comment]
edited out the storybook-task because I want to conentrate on testing for the moment. I will tackle the whole storybook-aspect at a later point.

**Comment by yannhn** [comment]
inserted the inclusion of a button to open up the form as a task

**Comment by yannhn** [comment]
edited out the testing part to do this later as part of a developer story
