### ISSUE TITLE
Display walks

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#16]
## User Story
As a user 
I want  to be able to see a section with the walks I did with my dog
So that I can have a overview over them

## AC
- [ ]  a card that displays the walks with the dog

## Tasks
- [ ] create new branch
- [ ] create component for the item-card to display the walks the user did with his/her dog
- [ ] add text-element with placeholder-data to show how long the last dog walk was
- [ ] add text-element with placeholder-data to show when the last dog walk was
- [ ] add text element with placeholder-data to show how long the dog has been outside today and how much time he should still be outside today
- [ ] apply basic styling to card
- [ ] add to storybook
- [ ] add testing

## Complexity
S
