### ISSUE TITLE
Display "business"

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#18]
## User Story
As a user 
I want  to be able to see a section of the „business“ my dog did today
So that I can have a quick overview over them

## AC
- [ ]  a card that displays the „business“ a dog did today

## Tasks
- [ ] create new branch
- [ ] create component for the item-card to display the business the dog did today
- [ ] add text-element with placeholder-data to show what kind of business it was
- [ ] add text-element with placeholder-data to show when the dog did his/her business
- [ ] add text element with placeholder-data to show the overall business the dog did on the day
- [ ] apply basic styling to card
- [ ] add testing

## Complexity
S

**Comment by lkk95** [comment]
Looks good to me :blush:
