### ISSUE TITLE
Add "business"

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#19]
## User Story
As a user 
I want  to add the „business“ I did with my dog already
So that I can see what „business“ my dog already did at that day

## AC
- [x] an option to add new new „business“
- [x] the user should be able to open up a input-selection
- [x] the user should have an option to select between the kind of „businesses“ the dog did
- [x] the user should be able to input the time of day 
- [x] a visual cue to show what kind of „business“ the dog did the last time
- [x] a visual cue to show when the dog did his „business“ the last time

## Tasks
- [x] create new branch
- [x] add inputBusiness-component
- [x] add a form so that the user can input when and what kind of business the dog did the last time
- [x] apply basic styling to form
- [x] add a button to the displayBusiness-component to display the form
- [x] connect the inputBusiness-component to the button-click on the displayBusiness-component (?conditional templates)
- [x] update given displayBusiness-component with the submitted input

## Complexity
M

## Depends on 
#18

**Comment by yannhn** [comment]
edited out the testing part to do this later as part of a developer story

**Comment by lkk95** [comment]
This also looks good 👍🏼
