### ISSUE TITLE
Cancel forms

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#25]
## User Story

As a user
I want to be able to cancel the input-selection
so that I am able get back if I changed my mind about it

## Design/Wireframe
![cancel_form](https://user-images.githubusercontent.com/100389763/177035425-267515c1-bf75-4749-9b79-8e8f23ac6570.png)

## AC
- [ ] the user should see a button to cancel the input-form
- [ ] the user should then be able to get back from the form

## Tasks
- [ ] create new branch
- [ ] add a button to the form-component
- [ ] connect the button the showForm-state to exit the form and just show the Card

## Complexity
S

## Depends on
#41
