### ISSUE TITLE
Show history of food

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#27]
## User Story
As a user
I want to be able to see a history of the amount of food the dog ate the last days
so that I can orientate myself on the last few days

## Design/Wireframe
![food_history(2)](https://user-images.githubusercontent.com/100389763/177035959-8d2ab3bb-f198-421d-8e9c-3d917f0b2454.png)

## AC
- [x] the user should see a button to open up a history of the last days
- [x] the user then should see his/her inputs of the last days
- [x] the user should be able to cancel the form and get back from the history

## Tasks
- [x] create new branch
- [x] add date-Object to existing components
- [x] add showHistoryFood-component
- [x] add a list to show of the last events 
- [x] sort the list via the date (?sort-method)
- [x] apply basic styling to showHistory-component
- [x] add a button to the foodCard-component
- [x] connect the showHistoryFood-component to the button-click on the foodCard-component (?conditional templates)

## Complexity
M
