### ISSUE TITLE
Show history of business

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#28]
## User Story
As a user
I want to be able to see a history of businesses my dog did for the last days
so that I can orientate myself on the last few days

## Design/Wireframe
![business_history](https://user-images.githubusercontent.com/100389763/177036462-17a3fbed-0f66-41a6-af9d-5974f3029827.png)

## AC
- [x] the user should see a button to open up a history of the last days
- [x] the user then should see his/her inputs of the last days
- [x] the user should be able to cancel the form and get back from the history

## Tasks
- [x] create new branch
- [x] add date-Object to existing components
- [x] add showHistoryBusiness-component
- [x] add a list to show of the last events 
- [x] sort the list via the date (?sort-method)
- [x] apply basic styling to showHistory-component
- [x] add a button to the businessCard-component
- [x] connect the showHistoryBusiness-component to the button-click on the BusinessCard-component (?conditional templates)

## Complexity
M
