### ISSUE TITLE
Show forms as overlay modal

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#29]
## Developer Story
As a developer 
I would like the forms to be displayed as an overlay over the homepage 
So that it looks way tidier 

## Design/Wireframe
![modal_overlay](https://user-images.githubusercontent.com/100389763/177037115-51c8b1ad-52be-4e5e-88dc-00fb74c608b5.png)

## AC
- [ ] the forms should overlay the actual page
- [ ] the background should be greyed-out/blurred out so that the focus lies on the form
- [ ] button click to open up the form should open up a modal

## Tasks
- [ ] create new branch
- [ ] create modal-component 
- [ ] apply styling so that the focus lies on the form

## Complexity
S
