### ISSUE TITLE
Calendar-view

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#3]
## User Story
As a user
I want to have a calendar
So that I can see on which day events are planned

## AC
- [x] a calendar with a monthly-view
- [x] the calendar shown on the Calendar/ToDo-page
- [x] Days with upcoming events are marked

## Design/Wireframe
![Calendar_](https://user-images.githubusercontent.com/100389763/174760891-5eaf12ab-ff9a-4e92-9643-315f6eabb7cb.png)

## Tasks
- [x] create a new branch
- [x] decide upon a calendar-library
- [x] create a component for the calendar 
- [x] apply basic styling
- [x] insert calendar-component into the Calendar/ToDo-page

## Complexity
L

**Comment by mbosselmann** [comment]
Hi Yannik,
I like the feature that you want to to implement! 👍  But I have some remarks you should think about.
- I like your value proposition, but I'm not sure if your value proposition matches your overall feature as in the end no events will be displayed after implementing the calendar. Maybe you should downgrade the why of this feature to something like "to see on which day events are planned". 🤔 
- For your acceptance criteria and your tasks you can work with checkboxes by writing "- [ ]" for your workflow. By using checkboxes you can see which tasks and criteria you have fulfilled and which you are working on. ☑️ 
- I like your description/ wireframe part, but I would put it above the acceptance criteria as this is the structure I use to know: First you need to see a description of what the feature will look like, then you can see what the criteria need to be fulfilled to implement the feature from a user perspective.
- For your scribble: I think it should be useful for the user to read something about the calendar (why is there a calendar or what does the marked days show) to understand why they see this calendar. (If this user story is part of another feature that will explain this and that will be implemented first, you should link to that user story for better understanding of this user story).
- You wrote "create a component for the calendar (?in storybook)". I think you could split this up like the following example:
  - [ ] Create a calendar component
  - [ ] Implement calendar functionality
  - [ ] Apply basic styling
  - [ ] Add to Storybook 
  - [ ] Add testing
As this example is quite detailed, you can also merge this to one task. I just thought about splitting this up to give you some inspiration. :)
- To estimate how you long it may take to finish this user story, you could add **Complexity** as another section at the end of your user story and say if this is a small, medium or large user story for you.

I hope my remarks are helpful! If you have any further questions, please feel free to contact me. :)

**Comment by mbosselmann** [comment]
Hi Yannik,
ok! 👍 I just have one question: Will the text de displayed? 🤔 Otherwise there won't be a note for the user to know what the calendar shows or?

**Comment by yannhn** [comment]
Hi mareike, 
thanks for the remarks! I want the calender to invert (flips) when the user clicks a marked day so that the calender than shows the todos of the day. 

You are right that the user at the moment does not know what a marked elements stands for. I have yet to think about how I implement those ui-instructions. I wanted to look into that as soon I finish the invert (flip) of the calender. I hope that it maybe would be self-explanatory but I have to look into that.

**Comment by yannhn** [comment]
Hi Mareike,
that is acually the plan. I first want to add the basic calendar-component as shown above and then show the todos under the calender as a sub-step. I then want to implement the flip of the calender in a seperate user story.
