### ISSUE TITLE
Show overall walks (in time) for the day

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#30]
## User Story
As a user 
I want to see how much time I was outside with my dog at a day
to have a quick overview about it

## Design/Wireframe
![timeoutside_sum](https://user-images.githubusercontent.com/100389763/177037874-b8d178b4-977c-49fc-8603-9e03085cff0e.png)

## AC
- [x] show total amount of walks in times

## Tasks
- [x] create new branch
- [x] add the time-inputs to sum up the total time outside

## Complexity
M
