### ISSUE TITLE
Update food component

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#31]
## Developer Story
As a developer
I want to update my inputFood-component
to use the data later on

## AC
- [ ] show the last inputted food items the dog ate

## Tasks
- [ ] create new branch
- [ ] use the map.method to display the submitted foodItems

## Complexety
M
