### ISSUE TITLE
Create a reusable Card-component for the Activities

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#32]
## Developer Story
As a developer
I want to have a reusable Card-component
to reduce the amount of redundant styling

## AC 
- [ ] every activity card should have a similar look

## Tasks 
- [ ] create new branch
- [ ] create card-component 
- [ ] apply basic styling
- [ ] use children.prop to implement the card-component as a container for the activites 

## Complexity
S
