### ISSUE TITLE
ToDo on calendar-day

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#36]
## User Story
As a user
I want to see todos for a marked day in the calendar
so that I can see what I have to do on that specific day

## AC
- [ ] show the todos for the specific day 
- [ ] the todos should be displayed below the calendar

## Tasks
- [ ] create a new branch
- [ ] create todo-component
- [ ] input mock-data for the todos
- [ ] apply basic-styling
- [ ] insert todo-component into the Calendar/ToDo-page

## Complexity
L
