### ISSUE TITLE
Show overall amount of food the dog ate

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#39]
## User Story
As a user 
I want to see how much food my dog ate
to have a quick overview about it

## Design/Wireframe
![todo_example(1)](https://user-images.githubusercontent.com/100389763/177275012-39cd469e-f339-4247-8468-600e5f1683dd.png)

## AC
- [x] sum up the submitted-inputs of food
- [x] show total amount of food the dog ate

## Tasks
- [x] create new branch
- [x] create counter-element in the displayFood-component
- [x] add the amount-inputs to sum up to a total amount of the inputs
- [x] show the sum in the counter

## Complexity
M
