### ISSUE TITLE
Navigation to calendar-page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#4]
As a user
I want to navigate to a calendar page
So that I see the calendar of the app

## AC
- [] have a Calendar-Page to navigate to 
- [] an option to navigate to different 
pages off the app
- [] the navigation should always be
visible
- [] it should show which page I selected

## Design/Wireframe
! [image:CC5C67BD-94EC-43F0-8147-7123F0208FB6-1107-000000160F79FBE6/Calendar_nav.png]

## Tasks
- [] create a new branch
- [] create a footer-component
- [] create Calendar-item within the footer-component
- [] implement React-Router
- [] implement NavLink to direct the user to the Calendar-page
