### ISSUE TITLE
Add navigation for Home and ToDo/Calendar-Page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#43]
## Developer story
As a developer
I want to add a navigation
so that I can select through different pages

## Design/Wireframe
![navigation](https://user-images.githubusercontent.com/100389763/177534565-99f829db-017b-4d8d-8039-a9891189d58c.png)

## AC
- [ ] the user should see a footer where the navigational-elements are stored
- [ ] the user should be able to select between two navigational-elements
- [ ] the user should always see the footer on every page
- [ ] the user should see which element is selected

## Tasks 
- [ ] create new branch
- [ ] add footer
- [ ] add navigational-elements within the footer
- [ ] implement react router
- [ ] create navLinks directing to the pages
- [ ] apply styling to show which element is active

## Complexity
M
