### ISSUE TITLE
user story / show overall business-amount of the day

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#45]
## User Story
As a user
I want to see the business my dog did today
so that I can have a quick overview of it

## AC
- [ ] sum up the submitted-inputs of business
- [ ] show total amount of the business the dog made
- [ ] split the amount into small or big

## Tasks
- [ ] create new branch
- [ ] create counter-element in the displayBusiness-component
- [ ] add the amount-inputs to sum up to a total amount of the inputs
- [ ] show the sum in the counter

## Complexity
M
