### ISSUE TITLE
Add todos

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#48]
## User Story
As a user 
I want to add todos 
so that I can plan the things surrounding my dog

## Design/Wireframe
![counter_amount(1)](https://user-images.githubusercontent.com/100389763/177941143-865f24af-cda7-4282-a814-784837c28ca8.png)

## AC 
- [x] the user should have an option to add todos
- [x] the user should see the todos on the todo/calendar-page
- [x] the user should be able to check the todos

## Tasks 
- [x] create a new branch
- [x] add a form to add todos
- [x] show new todos after submit
- [x] apply basic styling to form
- [x] add button to todo-component 
- [x] show Form on button click
