### ISSUE TITLE
Edit todos

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#49]
## User Story
As a user
I want to be able to edit todos
so that I do not have to create new ones if I changed my mind

## AC 
- [ ] the user should see an option to edit the todos
- [ ] after editing the todo should be visible at the same place

## Tasks
- [ ] create new branch
- [ ] create button on todo-component
- [ ] enable option to edit text-input after button click
