### ISSUE TITLE
Add Food-component

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#5]
## User Story
As a user 
I want to add the food that my dog already ate
So that I can see how much food the dog should eat afterwards

## Design/Wireframe
![addFood3](https://user-images.githubusercontent.com/100389763/174779342-03457979-b540-4da2-87ed-3fb74cb610ed.png)

## AC
- [x]  an option to add new food items
- [x] user can input amount of food and time of day
- [x] a visual cue to show how much food the dog already ate on that day
- [x] a visual cue to show how much food the dog has left to eat for the day
- [x] user should see when the dog had something to eat

## Tasks
- [x] create new branch
- [x] create component for the item-card to display the input
- [x] apply basic styling to item-card
- [x] add inputFood-component
- [x] connect the inputFood-component to the button-click (?conditional templates)
- [x] add a form so that the user can input what and when the dog ate
- [x] apply basic styling to inputFood-component
- [x] add text-element when the dog ate the last time to item-card
- [x] add text-element as a goal of how much food the dog should eat in one day (for example 0(current) /100gram (goal))

## Complexity
M

**Comment by mbosselmann** [comment]
Hi Yannik,
I like your user story! 👍 Just some nit-picking remarks: 
- I would place the acceptance criteria below the description and not vice versa. :)
- In your tasks you have "apply basic styling" three times and only once with "to form". I would also add to the other "apply basic styling" tasks for which component. 
- I don't understand "add text-element how"
- You could also add Storybook and testing as tasks if you want to

And one question: Until now I have seen two user stories from you and I'm currently not sure which one is the first user story you want to start with. Can you tell me to better understand how these user stories link together? Or should we discuss this together? 🤔

**Comment by yannhn** [comment]
Hi Mareike,
thanks for the feedback! I already implemented it in the user story.
Regarding your question: At the moment moment I am writing my sixth user story which will also be the last one for today. I structured it a bit in my projects-view but at the moment I want to concentrate on the homepage. My order in which I want to tackle the stories:

1) Show name
2) Show picture
3) Update name and picture
4) Input information like how much food the dog needs at a day which should be shown in the addFood-Component (currently writing it)
5) Add Food

The Calendar-component will be shown on a seperate page so I will work on this user stories at a later time.
We can also discuss it together if you want (and have the time of course)!

**Comment by mbosselmann** [comment]
Hi Yannik,
thank you very much for your answer! ❤️ I think that this structure is logic and will work for you! And it also seems logic to me to implement the calendar component later. 👍

**Comment by yannhn** [comment]
edited out the storybook-task because I want to conentrate on testing for the moment. I will tackle the whole storybook-aspect at a later point.

**Comment by yannhn** [comment]
edited out the testing part to do this later as a developer-story.
