### ISSUE TITLE
Delete todos

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#50]
## User Story
As a user
I want to be able to edit todos
so that I do not have to create new ones if I changed my mind

## AC 
- [ ] the user should see an option to edit the todos
- [ ] after deleting the todo should be gone

## Tasks
- [ ] create new branch
- [ ] create button on todo-component
- [ ] enable option to delete todo after button click
