### ISSUE TITLE
Check todos

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#53]
## User Story
As a user 
I want to check todos
so that I can mark them as accomplished

## Design/Wireframe
![todos_log](https://user-images.githubusercontent.com/100389763/178111982-26de9f8f-b481-4aa8-94cb-c2b3a45754dc.png)

## AC
- [x] the user should have an option to mark todos as checked
- [x] when the todo is checked it should move to a different log-section
- [x] the user should see every checked todo in that section

## Tasks
- [x] create new branch
- [x] create log-section
- [x] add checkbox to todos
- [x] filter checked todos to move into the log-section
