### ISSUE TITLE
design homepage

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#57]
## User story
As a user 
I want to apply styling to the homepage
to reach the design-goal

## Design/Wireframe
![design-goal](https://user-images.githubusercontent.com/100389763/178341945-467592a5-6cce-4bac-ac7d-68753ca714cd.png)

## AC
- [ ] the design should look like the design goal
- [ ] the activity-cards should have the same design
- [ ] the footer should consists of pictures/svgs
- [ ] there should be a placeholder-image for the image-upload

## Tasks
- [ ] create new branch
- [ ] replace the footer-text with svg's
- [ ] add placeholder-image for info
- [ ] apply global-style to background
- [ ] use reusable design for activity-cards to lessen redundant code
- [ ] move show food goal into card

**Comment by yannhn** [comment]
Oh you are totally right. A user story makes more sense here. I will change it!

**Comment by JessicaLoers** [comment]
I'm sorry @yannhn , I think you need to make more changes than just change Value proposition from Developer to User, because the user don't know nothing about your design goals 😁

_Example for the Value proposition_
**As I User**
**I want** a intuitive and clear design
**So that **  it makes fun to use .... or something like that. 

_Example for the AC_ 
- the size of the button should be.... _whatever_
- .... 

**Please try again** 🫣
