### ISSUE TITLE
Show Name 

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#6]
## User Story
As a user 
I want  to see the name of my dog on the homepage
So that it is always clear which dog it is

## Design/Wireframe
![Name](https://user-images.githubusercontent.com/100389763/174784124-bac47eaf-4079-4153-91e4-9010ec4230a9.png)

## AC
- [x] a title that shows the name of the dog
- [x] the title shown on the homepage

## Tasks
- [x] create a new branch
- [x] create a component for the title
- [x] write provisionally title 
- [x] apply basic styling

## Complexity
S

**Comment by JessicaLoers** [comment]
Well done 🙂

**Comment by yannhn** [comment]
Thanks!
