### ISSUE TITLE
design calendar-page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#62]
## User story
As a user 
I want to apply styling to the calendar-page
to reach the design-goal

## Design/Wireframe
![design-goal(1)](https://user-images.githubusercontent.com/100389763/178809921-c2fecebd-3cc4-4eb4-a0d8-108f08bee59c.png)

## AC
- [ ] the design should look like the design goal
- [ ] the activity-cards should have the same design
- [ ] the footer should consists of pictures/svgs
- [ ] there should be a placeholder-image for the image-upload

## Tasks
- [ ] create new branch
- [ ] replace the footer-text with svg's
- [ ] apply global-style to background
- [ ] style calendar

**Comment by lkk95** [comment]
I really like your design!:rocket:
