### ISSUE TITLE
design todo-page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#63]
## User story
As a user 
I want to apply styling to the todo-page
to reach the design-goal

## Design/Wireframe
![design-goal(2)](https://user-images.githubusercontent.com/100389763/178810091-6e8d906d-c0aa-4ce6-8686-3c64ec69960a.png)

## AC
- [ ] the design should look like the design goal
- [ ] the activity-cards should have the same design
- [ ] the footer should consists of pictures/svgs
- [ ] there should be a placeholder-image for the image-upload

## Tasks
- [ ] create new branch
- [ ] replace the footer-text with svg's
- [ ] apply global-style to background
- [ ] style calendar
