### ISSUE TITLE
input todos without a form

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#64]
## User Story
As a user
I want to input todos without opening a new window
so that I can add todos in a faster way

## AC
- [ ] the user should see an input-field to add todos

## Tasks 
- [ ] create new branch
- [ ] remove form
- [ ] add input-field directly into card
