### ISSUE TITLE
Add navigation for todo-page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#66]
## Developer story
As a developer
I want to add a navigation
so that I can select through different pages

## Design/Wireframe
![design-goal(3)](https://user-images.githubusercontent.com/100389763/178812534-292facf9-95d4-4d2a-a0f3-5acdada9c57f.png)

## AC
- [ ] the user should see a footer where the navigational-elements are stored
- [ ] the user should be able to select between two navigational-elements
- [ ] the user should always see the footer on every page
- [ ] the user should see which element is selected

## Tasks 
- [ ] create new branch
- [ ] add footer
- [ ] add navigational-elements within the footer
- [ ] implement react router
- [ ] create navLinks directing to the pages
- [ ] apply styling to show which element is active

## Complexity
M
