### ISSUE TITLE
Add events to calendar

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#67]
## User Story
As a user
I want to add events to the calendar
so that I can plan events with my dog

## AC 
- [x] the user should be able to create events
- [x] the events should than be able to move to different dates

## Tasks 
- [x] create new branch
- [x] add a footerbar to calendar to store events
- [x] handle option to create events
- [x] enable drag and drop to move the events to the single dates

## Complexity
L
