### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#68]
## Developer story
As a developer
I want to add local storage to my app
so that the data is stored after refreshing the site

## AC
- [ ] the data should be stored after refreshing the page
- [ ] moving to a different page should not delete the inputs

## Tasks
- [ ] create new branch
- [ ] add custom-hook for localStorage
- [ ] use hook to store local storage for activities, calendar and todos
