### ISSUE TITLE
Show Picture

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#7]
## User Story
As a user 
I want  to see a picture of my dog
So that it is always clear which dog it is

## Design/Wireframe
![picture](https://user-images.githubusercontent.com/100389763/174799006-e6da6eb0-d99d-48e5-96de-e37134aa8e91.png)

## AC
- [x] a picture that shows the dog
- [x] the picture shown on the homepage

## Tasks
- [x] create a new branch
- [x] create a component for the picture
- [x] input mock picture
- [x] apply basic styling

## Complexity
S

**Comment by JessicaLoers** [comment]
👍 
Just two little typos: 

-  So that "it" is always clear which dog it is 
-  The "n" of Design has somehow slipped under the picture

**Comment by yannhn** [comment]
Thanks!
