### ISSUE TITLE
Input Picture without always inputting name

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#70]
## User Story
As a user
I want to update the picture for my dog seperate from the name
so that I can change the picture more frequently 

## AC
- [x] the user should be able to update only the picture
- [x] the upload should be seperated from the name-input

## Tasks 
- [x] create new branch
- [x] seperate the name input from image submit
- [x] create a button to handle the upload via form
