### ISSUE TITLE
NOCH INS REV // Have a page to hold the settings

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#71]
## User Story
As a user 
I want to have a page to update the settings
so that I can configurate them when I want

## AC 
- [ ] the user should see a navigational-element in the footer
- [ ] the user should be able to input the info settings as well es the amount of food the dog should eat in one day
- [ ] the data should be visible in the other pages

## Tasks
- [ ] create new branch
- [ ] add new settings-page
- [ ] create navigation to new settings-page
- [ ] move the info-settings from the homepage to the new page
