### ISSUE TITLE
header component

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#72]
## User story
As a user 
I want to have a different title for each page
so that I can easily distingish the pages

## AC
- [ ] the user should be able to see a header on the different pages
- [ ] the header should always have the same style

## Tasks
- [ ] create new branch
- [ ] create header-component
- [ ] connect header-component with routing
- [ ] update name on selected route
