### ISSUE TITLE
NOCH INS REV //Show Food Goal as button in Card

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#73]
## User Story
As a user 
I want to add the food goal for the day in the Activity-Card
so that I can easily change the goal for the day

## AC
- [ ] the user should be able to update the food-goal via a button in the activity-card

## Tasks
- [ ] create new branch
- [ ] move inputGoal-button in the foodCard-Component
- [ ] display goal in the foodCard
