### ISSUE TITLE
Update name and picture

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#8]
## User Story
As a user 
I want to add informations of my dog
So that I make the app about my dog

## AC
- [ ] an option to update any given information of the dog on the homepage
- [ ] the user should be able to change the name, a new profile-picture
- [ ] the information entered should also be usable in the other components like the Add food-item
 
## Tasks
- [ ] create a new branch
- [ ] create button to open up input-information on the homepage
- [ ] create a input-information component
- [ ] add a form so that the user can update the name and the picture
- [ ] connect the input-information component to the button-click (?conditional templates)
- [ ] apply basic styling
- [ ] add storybook
- [ ] add testing

## Complexity
M

**Comment by yannhn** [comment]
edited out the storybook-task because I want to conentrate on testing for the moment. I will tackle the whole storybook-aspect at a later point.

**Comment by yannhn** [comment]
edited out the testing part to do this later as a developer story
