### ISSUE TITLE
Checkbox if the dog did not do any business

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#80]
## User Story
As a user
I want to select an option that the dog did not do any of his business
so that I can see when I/he was not successfull

## AC 
- [x] the user should have an option to select 'no business'
- [x] this input should then be displayed in the card

## Tasks
- [x] create a new branch
- [x] create new checkbox in the inputBusiness-component
- [x] show result in the card
