### ISSUE TITLE
Refactor activity-card

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#84]
## Developer Story
As a developer 
I want to refactor my activity-Cards
so that I can lessen redundant repitive code

## AC
- [ ] there should be a Card-Component which holds the content
- [ ] the styling of the component should be reusable

## Tasks
- [ ] create new branch
- [ ] create form-component
- [ ] insert activity-content into form
