### ISSUE TITLE
Delete unnecessary files

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#85]
## Developer Story
As a developer
I want to delete unneccessary files
so that I have a better file structure

## AC
- [ ] delete files and folders that currently are not in use

## Tasks
- [ ] create new branch
- [ ] delete button and inputLabel files
- [ ] delete other unneccessary files
