### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#86]
## Developer story
As a developer
I want to have a better file-structure
so that I can have a better overview over them

## AC 
- [x] setup better file-structure
- [x] create folder structure that holds similar components

## Tasks
- [ ] create new branch
- [x] create folder for activities
- [x] create folder for forms
- [x] create folder for todos
- [x] create folder for calendar
