### ISSUE TITLE
Input food goal for the day

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#9]
## User Story
As a user
I want to add how much food my dog should eat in a day
So that I can see how much food my dog should eat

## Design/Wireframe
![update_food_goal(4)](https://user-images.githubusercontent.com/100389763/174829567-3b079492-4133-47f5-be96-74a5ff7a03bc.png)

## AC
- [x] an option to update the amount of food the dog should eat in one day
- [x] the user should always be able to update the daily-goal
- [x] the information the user entered should be usable in the Add-food-item-component

## Tasks
- [x] create a new branch
- [x] create button to open input-information on the homepage
- [x] create a input-food-goal component
- [x] connect the input-food-goal-component to the button click (?conditional templates)
- [x] apply basic styling

## Complexity
M

**Comment by mbosselmann** [comment]
Hi Yannik, 
I like your user story! Your rock! 🪨 I only have one question: I think I don't understand why the plus means "there has not been declared a daily goal yet". Can you explain this to me? 🤔 Does the plus opens the form? Because the arrow that indicates the button to open the form does not refer to the "+" symbol.

**Comment by yannhn** [comment]
Hi Mareike, 
thanks for the feedback and the kind words! The form should be displayed by clicking on the "+"-symbol. I placed the arrow somewhat awkwardly. The arrow should simply indicate the number of grams and thus show the status before something was entered via the form.

**Comment by mbosselmann** [comment]
Hi Yannik,
ok! 👍 Your explanation totally makes sense!

**Comment by yannhn** [comment]
edited out the storybook-task because I want to conentrate on testing for the moment. I will tackle the whole storybook-aspect at a later point.

**Comment by yannhn** [comment]
edited out the testing part to do this later as part of a developer story
