### ISSUE TITLE
Refactor Styling for Calendar-page

### ISSUE THREAD

**Issue by yannhn** [yannhn/capstone-project#90]
## Developer Story
As a developer
I want to refactor my styling-components on the calendar-page
so that I have less repetetive code

## AC 
- [ ] lessen the amount of code 

## Tasks
- [ ] create new branch
- [ ] make more use of global styles
- [ ] lessen repetetive and redundant code
